In [45]:
import itertools
import pandas as pd
import numpy as np
from scipy.stats import norm

print("APM111 - FA6\nRachelle Erika D. Borja")

# Number 1. Answer 8.18 using Python or R
population = [9,12,15]
N = len(population)

# Generate samples (n = 2 with replacement)
samples = list(itertools.product(population, repeat=2))

# Table
df = pd.DataFrame(samples, columns=["A","B"])
df["C"] = df.mean(axis=1)
df["D"] = ""
df["E"] = ""
df["F"] = ""
df["G"] = ""

# Sampling distribution values
xbar_vals = np.array([9,10.5,12,13.5,15])
prob_vals = np.array([1/9,2/9,3/9,2/9,1/9])

# Rows
for i,(x,p) in enumerate(zip(xbar_vals,prob_vals)):
    df.loc[i,"D"] = x
    df.loc[i,"E"] = p
    df.loc[i,"F"] = x*p
    df.loc[i,"G"] = (x**2)*p

df.loc[5,"F"] = 12
df.loc[5,"G"] = 147

# Remove unwanted and trailing zeros
df = df.replace(0,"")

def clean_num(x):
    if isinstance(x,(int,float)):
        return f"{x:g}"
    return x

df = df.map(clean_num)

# Header row
header = pd.DataFrame(
    [["","","mean","xbar","p(xbar)","xbar × p(xbar)","xbar² × p(xbar)"]],
    columns=df.columns
)

table = pd.concat([header,df],ignore_index=True)

print("\n" + "-" * 80 + "\n")
print("Answer for 8.18 using Python\n\nSOLUTION")

display(table.style.hide(axis="index"))

print("\nAnswer for 8.18 verifications\n")

# Population mean
mu = np.mean(population)

# Population variance
sigma2 = np.sum((np.array(population)-mu)**2)/N

print("Population:", population)
print("Population Mean (μ) =", mu)
print("Population Variance (σ²) =", sigma2)

# Verify μ_x̄ = μ
mu_xbar = np.sum(xbar_vals * prob_vals)

print("\nVerification of μ_x̄ = μ")
print("μ_x̄ = Σ x̄P(x̄)")
print("μ_x̄ = 9(1/9) + 10.5(2/9) + 12(3/9) + 13.5(2/9) + 15(1/9)")
print("μ_x̄ =", round(mu_xbar, 1))
print("μ =", mu)

# Verify σ²_x̄ = σ² / 2
sum_xbar2p = np.sum((xbar_vals**2)*prob_vals)

var_xbar = sum_xbar2p - mu_xbar**2

print("\nVerification of σ²_x̄ = σ² / 2")
print("Σ x̄²P(x̄) =", sum_xbar2p)
print("σ²_x̄ = Σ x̄²P(x̄) - (μ_x̄)²")
print("σ²_x̄ =", sum_xbar2p, "-", round(mu_xbar**2, 1))
print("σ²_x̄ =", round(var_xbar, 1))

print("\nCheck formula:")
print("σ² / 2 =", sigma2, "/ 2 =", sigma2/2)

print("\n\nTherefore μ_x̄ = μ, and σ²_x̄ = σ² / 2")

print("\n" + "-" * 80 + "\n")

# *************************************************
# Number 2. Answer 8.21, and 8.34
# For problem 8.21
population = [3,7,11,15]
N = len(population)

print("Answer for 2.21\n")
print("Population:", population)

# (a) Population Mean μ
print("\n(a) Population Mean")

print("Formula: μ = (Σx) / N")

sum_x = np.sum(population)
mu = sum_x / N

print("Σx = 3 + 7 + 11 + 15 =", sum_x)
print("N =", N)
print("μ =", sum_x, "/", N)
print("μ =", mu)

# (b) Population Standard Deviation σ
print("\n(b) Population Standard Deviation")

print("Formula: σ² = Σ(x − μ)² / N")

deviations = population - mu
squared_dev = deviations**2
sum_sq = np.sum(squared_dev)

sigma2 = sum_sq / N
sigma = np.sqrt(sigma2)

print("\nTable of Computations")
for x,d,sq in zip(population,deviations,squared_dev):
    print("x =",x,"  x-μ =",d,"  (x-μ)² =",sq)

print("\nΣ(x-μ)² =", sum_sq)
print("σ² =", sum_sq, "/", N)
print("σ² =", sigma2)

print("\nσ = √σ²")
print("σ = √",sigma2)
print("σ =",round(sigma, 1))

# (c) Mean of Sampling Distribution
print("\n(c) Mean of the Sampling Distribution of Means")

print("Formula: μ_x̄ = μ")

mu_xbar = mu

print("μ_x̄ =",round(mu_xbar, 1))

# (d) Standard Deviation of Sampling Distribution
print("\n(d) Standard Deviation of the Sampling Distribution")

print("Formula: σ_x̄ = σ / √n")

n = 2
sigma_xbar = sigma / np.sqrt(n)

print("σ_x̄ =",round(sigma,1),"/ √",n)
print("σ_x̄ =",round(sigma_xbar, 1))

# Verification
print("\nVerification of (c)")

print("Using formula: μ_x̄ = μ")

print("μ =",mu)
print("μ_x̄ =",mu)

print("\nVerification of (d)")

print("Using formula: σ²_x̄ = σ² / n")

sigma_xbar2 = sigma2 / n

print("σ² =",sigma2)
print("σ²_x̄ =",sigma2,"/",n)
print("σ²_x̄ =",sigma_xbar2)

print("\nσ_x̄ = √σ²x̄")
print("σ_x̄ = √",sigma_xbar2)
print("σ_x̄ =",round(np.sqrt(sigma_xbar2),1))

print("\n" + "-" * 80 + "\n")


# For problem 8.34
n = 200
p = 0.5

print("Answer for 8.34\n")
print("Number of births (n) =", n)
print("Probability of boy (p) =", p)

# Mean of sampling distribution
print("\nMean of sampling distribution")
print("Formula: μ_p̂ = p")

mu = p

print("μ_p̂ =", round(mu,5))

# Standard deviation of sampling distribution
print("\nStandard deviation of sampling distribution")
print("Formula: σ_p̂ = √[ p(1-p) / n ]")

sigma = np.sqrt(p*(1-p)/n)

print("σ_p̂ = √[",p,"×",1-p,"/",n,"]")
print("σ_p̂ = √(",p*(1-p)/n,")")
print("σ_p̂ =", round(sigma,6))

# (a) Less than 40% boys
print("\n(a) Probability that less than 40% will be boys")

phat_a = 0.40

print("Formula: z = (p̂ - μ) / σ")

z_a = (phat_a - round(mu,5)) / round(sigma,6)

print("z =", "(0.40 -",round(mu,5),") /", round(sigma,6))
print("z =", round(z_a,3))

prob_a = norm.cdf(z_a)

print("P(p̂ < 0.40) = Φ(z)")
print("P =", round(prob_a,5))

# (b) Between 43% and 57% girls
print("\n(b) Probability that between 43% and 57% will be girls")

lower = 0.43
upper = 0.57

print("Lower z-score")
z1 = (lower - round(mu,5))/ round(sigma,6)
print("z1 = (0.43 -",round(mu,5),") /", round(sigma,6))
print("z1 =", round(z1,2))

print("\nUpper z-score")
z2 = (upper - round(mu,5))/ round(sigma,6)
print("z2 = (0.57 -",round(mu,5),") /", round(sigma,6))
print("z2 =", round(z2,2))

prob_b = norm.cdf(z2) - norm.cdf(z1)

print("\nP(-1.98 < p̂ < 1.98)")
print("= Φ(z2) - Φ(z1)")
print("= ", round(prob_b,5))

# (c) More than 54% boys
print("\n(c) Probability that more than 54% will be boys")

phat_c = 0.54

z_c = (phat_c - round(mu,5))/ round(sigma,6)

print("z = (0.54 -",round(mu,5),") /", round(sigma,6))
print("z =", round(z_c,3))

prob_c = 1 - norm.cdf(z_c)

print("\nP(p̂ > 0.54)")
print("= 1 - Φ(z)")
print("=", round(prob_c,5))

# Table
table = pd.DataFrame({
    "Case":[
        "P(p̂ < 0.40)",
        "P(0.43 < p̂ < 0.57)",
        "P(p̂ > 0.54)"
    ],
    "Z-score":[
        round(z_a,5),
        f"{round(z1,5)} to {round(z2,5)}",
        round(z_c,5)
    ],
    "Probability":[
        round(prob_a,5),
        round(prob_b,5),
        round(prob_c,5)
    ]
})

print("\nFinals Answers for 8.34: (in Table Form)")
display(table.style.hide(axis="index"))

print("\n" + "-" * 80 + "\n")

# *************************************************
# Number 3. Answer 8.49.

print("Answer for 8.49\n")
# 8.49
x = [6, 9, 12, 15, 18]
p = [0.1, 0.2, 0.4, 0.2, 0.1]

# Population mean μ
mu = sum(xi*pi for xi,pi in zip(x,p))

# Population variance σ²
print("σ² = Σ (x - μ)^2 p(x)")
variance = sum(((xi-mu)**2)*pi for xi,pi in zip(x,p))

print("Population Mean (μ):", mu)
print("Population Variance (σ²):", variance)

# All possible samples of size 2 (replacement)
samples = list(itertools.product(x, repeat=2))

# Means and Probabilities
print("P(sample) = p(x1) * p(x2)")
rows = []

for s in samples:
    x1, x2 = s
    mean = round((x1 + x2) / 2, 2)
    prob = round(p[x.index(x1)] * p[x.index(x2)], 2)
    rows.append([x1, x2, mean, prob])

# Table
df = pd.DataFrame(rows, columns=[
    "x1",
    "x2",
    "Sample Mean (x̄)",
    "P(sample)"
])

print("\nAll Samples, Means, and Probabilities")
df.style.format({
    "Sample Mean (x̄)": "{:.2f}",
    "P(sample)": "{:.2f}"
}).hide(axis="index")

APM111 - FA6
Rachelle Erika D. Borja

--------------------------------------------------------------------------------

Answer for 8.18 using Python

SOLUTION

Answer for 8.18 verifications

Population: [9, 12, 15]
Population Mean (μ) = 12.0
Population Variance (σ²) = 6.0

Verification of μ_x̄ = μ
μ_x̄ = Σ x̄P(x̄)
μ_x̄ = 9(1/9) + 10.5(2/9) + 12(3/9) + 13.5(2/9) + 15(1/9)
μ_x̄ = 12.0
μ = 12.0

Verification of σ²_x̄ = σ² / 2
Σ x̄²P(x̄) = 147.0
σ²_x̄ = Σ x̄²P(x̄) - (μ_x̄)²
σ²_x̄ = 147.0 - 144.0
σ²_x̄ = 3.0

Check formula:
σ² / 2 = 6.0 / 2 = 3.0


Therefore μ_x̄ = μ, and σ²_x̄ = σ² / 2

--------------------------------------------------------------------------------

Answer for 2.21

Population: [3, 7, 11, 15]

(a) Population Mean
Formula: μ = (Σx) / N
Σx = 3 + 7 + 11 + 15 = 36
N = 4
μ = 36 / 4
μ = 9.0

(b) Population Standard Deviation
Formula: σ² = Σ(x − μ)² / N

Table of Computations
x = 3   x-μ = -6.0   (x-μ)² = 36.0
x = 7   x-μ = -2.0   (x-μ)² = 4.0
x = 11   x-μ = 2.0   (x-μ)² = 4.0
x = 15   x-μ = 6.0   (x-μ)² = 36.0

Σ(x-μ)² = 80.0
σ² = 80.0 / 4
σ² = 20.0

σ = √σ²
σ = √ 20.0
σ = 4.5

(c) Mean of the Sampling Distribution of Means
Formula: μ_x̄ = μ
μ_x̄ = 9.0

(d) Standard Deviation of the Sampling Distribution
Formula: σ_x̄ = σ / √n
σ_x̄ = 4.5 / √ 2
σ_x̄ = 3.2

Verification of (c)
Using formula: μ_x̄ = μ
μ = 9.0
μ_x̄ = 9.0

Verification of (d)
Using formula: σ²_x̄ = σ² / n
σ² = 20.0
σ²_x̄ = 20.0 / 2
σ²_x̄ = 10.0

σ_x̄ = √σ²x̄
σ_x̄ = √ 10.0
σ_x̄ = 3.2

--------------------------------------------------------------------------------

Answer for 8.34

Number of births (n) = 200
Probability of boy (p) = 0.5

Mean of sampling distribution
Formula: μ_p̂ = p
μ_p̂ = 0.5

Standard deviation of sampling distribution
Formula: σ_p̂ = √[ p(1-p) / n ]
σ_p̂ = √[ 0.5 × 0.5 / 200 ]
σ_p̂ = √( 0.00125 )
σ_p̂ = 0.035355

(a) Probability that less than 40% will be boys
Formula: z = (p̂ - μ) / σ
z = (0.40 - 0.5 ) / 0.035355
z = -2.828
P(p̂ < 0.40) = Φ(z)
P = 0.00234

(b) Probability that between 43% and 57% will be girls
Lower z-score
z1 = (0.43 - 0.5 ) / 0.035355
z1 = -1.98

Upper z-score
z2 = (0.57 - 0.5 ) / 0.035355
z2 = 1.98

P(-1.98 < p̂ < 1.98)
= Φ(z2) - Φ(z1)
=  0.95229

(c) Probability that more than 54% will be boys
z = (0.54 - 0.5 ) / 0.035355
z = 1.131

P(p̂ > 0.54)
= 1 - Φ(z)
= 0.12895

Finals Answers for 8.34: (in Table Form)

--------------------------------------------------------------------------------

Answer for 8.49

σ² = Σ (x - μ)^2 p(x)
Population Mean (μ): 12.0
Population Variance (σ²): 10.8
P(sample) = p(x1) * p(x2)

All Samples, Means, and Probabilities