In [67]:
import numpy as np
import pandas as pd
from scipy import stats

#APM 1111 - SA1 by Borja, Rachelle Erika D.

# Part I.
print("\n" + "-" * 80 + "\n")
print("Borja_SA1 - Part I.")
print("\n" + "-" * 80 + "\n")
# *******************************************************************
# Question 1: Descriptive statistical summaries of the Entire Dataset
# Raw Data from Table 10.6
males = [
12,4,11,13,11,
7,9,10,10,7,
7,12,6,9,15,
10,11,12,7,8,
8,9,11,10,9,
10,9,9,7,9,
11,7,10,10,11,
9,12,12,8,13,
9,10,8,11,10,
13,13,9,10,13
]

females = [
11,9,7,10,9,
10,10,7,9,10,
11,8,9,6,11,
10,7,9,12,14,
11,12,12,8,12,
12,9,10,11,7,
12,7,9,8,11,
10,8,13,8,10,
9,9,9,11,9,
9,8,9,12,11
]

# Combine entire dataset
data = np.array(males + females)

# Computing Statistics
n = len(data)

mean = np.mean(data)
median = np.median(data)
std = np.std(data, ddof=1)
variance = np.var(data, ddof=1)
minimum = np.min(data)
maximum = np.max(data)

skewness = stats.skew(data, bias=False)
kurtosis = stats.kurtosis(data, fisher=True, bias=False)

# Quartiles & Deciles
Q1, Q2, Q3 = np.percentile(data,[25,50,75])
deciles = np.percentile(data,[10,20,30,40,50,60,70,80,90])

# 95% Confidence Interval
alpha = 0.05
t_critical = stats.t.ppf(1 - alpha/2, df=n-1)

margin_error = t_critical * std / np.sqrt(n)

ci_lower = mean - margin_error
ci_upper = mean + margin_error

values = [
f"{n:.2f}",
f"{mean:.2f}",
f"{median:.2f}",
f"{std:.2f}",
f"{variance:.2f}",
f"{minimum:.2f}",
f"{maximum:.2f}",
f"{skewness:.4f}",
f"{kurtosis:.4f}",
f"{Q1:.2f}",
f"{Q2:.2f}",
f"{Q3:.2f}",
*[f"{d:.2f}" for d in deciles],
f"{ci_lower:.2f}",
f"{ci_upper:.2f}"
]

# Statistic Labels
statistics = [
"Sample Size (n)",
"Mean",
"Median",
"Standard Deviation",
"Variance",
"Minimum",
"Maximum",
"Skewness",
"Kurtosis",
"Q1 (25%)",
"Q2 (Median)",
"Q3 (75%)",
"D1 (10%)",
"D2 (20%)",
"D3 (30%)",
"D4 (40%)",
"D5 (50%)",
"D6 (60%)",
"D7 (70%)",
"D8 (80%)",
"D9 (90%)",
"95% CI Lower",
"95% CI Upper"
]

# Table
summary_table = pd.DataFrame({
"Statistic": statistics,
"Value": values
})

print("Descriptive Statistical Summaries of the Entire Dataset")

display(
summary_table.style
.hide(axis="index")
.set_properties(subset=["Statistic"], **{"text-align":"left"})
)

print("\n" + "-" * 80 + "\n")


# *******************************************************************
# Question 2: Descriptive statistical summaries grouped by gender
males = [
12,4,11,13,11,
7,9,10,10,7,
7,12,6,9,15,
10,11,12,7,8,
8,9,11,10,9,
10,9,9,7,9,
11,7,10,10,11,
9,12,12,8,13,
9,10,8,11,10,
13,13,9,10,13
]

females = [
11,9,7,10,9,
10,10,7,9,10,
11,8,9,6,11,
10,7,9,12,14,
11,12,12,8,12,
12,9,10,11,7,
12,7,9,8,11,
10,8,13,8,10,
9,9,9,11,9,
9,8,9,12,11
]

# Computing statistics
def compute_stats(data):

    data = np.array(data)

    n = len(data)
    mean = np.mean(data)
    median = np.median(data)

    std = np.std(data, ddof=1)
    variance = np.var(data, ddof=1)

    minimum = np.min(data)
    maximum = np.max(data)

    skewness = stats.skew(data, bias=False)
    kurtosis = stats.kurtosis(data, fisher=True, bias=False)

    quartiles = np.percentile(data,[25,50,75])
    deciles = np.percentile(data,[10,20,30,40,50,60,70,80,90])

    # Confidence interval
    alpha = 0.05
    t = stats.t.ppf(1-alpha/2, df=n-1)
    margin = t * std / np.sqrt(n)

    ci_lower = mean - margin
    ci_upper = mean + margin

    results = [
        f"{n:.2f}",
        f"{mean:.2f}",
        f"{median:.2f}",
        f"{std:.2f}",
        f"{variance:.2f}",
        f"{minimum:.2f}",
        f"{maximum:.2f}",
        f"{skewness:.4f}",
        f"{kurtosis:.4f}",
        f"{quartiles[0]:.2f}",
        f"{quartiles[1]:.2f}",
        f"{quartiles[2]:.2f}",
        *[f"{d:.2f}" for d in deciles],
        f"{ci_lower:.2f}",
        f"{ci_upper:.2f}"
    ]

    return results

# Computing male & female statistics
male_stats = compute_stats(males)
female_stats = compute_stats(females)

# Statistic Labels
labels = [
"Sample Size (n)",
"Mean",
"Median",
"Standard Deviation",
"Variance",
"Minimum",
"Maximum",
"Skewness",
"Kurtosis",
"Q1 (25%)",
"Q2 (Median)",
"Q3 (75%)",
"D1 (10%)",
"D2 (20%)",
"D3 (30%)",
"D4 (40%)",
"D5 (50%)",
"D6 (60%)",
"D7 (70%)",
"D8 (80%)",
"D9 (90%)",
"95% CI Lower",
"95% CI Upper"
]

# Table
table = pd.DataFrame({
"Statistic": labels,
"Male": male_stats,
"Female": female_stats
})

print("Descriptive Statistical Summaries Grouped by Gender")

display(
table.style
.hide(axis="index")
.set_properties(subset=["Statistic"], **{"text-align":"left"})
)

print("\n" + "-" * 80 + "\n")

# *******************************************************************
# Question 3: Statistical Report
print("Short Statistical Report")

print("\n1. Descriptive Statistics of the Entire Dataset")
print("\tThe dataset contains 100 observations of weekly phone usage.\n\tThe mean usage is 9.76 hours and the median is 10.00 hours,\n\tindicating that the typical weekly usage is around 10 hours.\n\tThe standard deviation is 1.96 hours, showing moderate\n\tvariability among individuals. Phone usage ranges from\n\t4–15 hours. The skewness is close to zero, suggesting a roughly\n\tsymmetric distribution, while the kurtosis is also near zero,\n\tindicating a distribution similar to normal. The middle 50%\n\tof the data lies between 9 and 11 hours based on the quartiles.")

print("\n2. Comparison Across Gender")
print("\tBoth gender groups show very similar phone usage patterns.\n\tMales have a mean of 9.82 hours, while females have a mean of\n\t9.70 hours. The standard deviation for males (≈2.15) is slightly\n\tlarger than for females (≈1.78), indicating slightly greater\n\tvariability among males. The usage ranges are 4–15 hours for\n\tmales and 6–14 hours for females, but both groups have medians\n\tclose to 10 hours like 10.0 hours for males, and 9.50 hours for\n\tfemales, suggesting similar central tendencies.")

print("\n3. Interpretation of the 95% Confidence Intervals")
print("\tThe 95% confidence interval for the overall mean is approximately\n\t(9.37, 10.15) hours, meaning the true population mean weekly phone\n\tusage likely falls within this range. For the gender groups, the\n\tintervals are approximately (9.21, 10.43) for males and (9.20, 10.20)\n\tfor females. Since these intervals overlap, there is no strong\n\tevidence of a difference in average phone usage between genders.")

print("\n4. Observed Patterns")
print("\tOverall, both genders display similar phone usage patterns, with\n\tmost values concentrated around 9–11 hours per week. While males\n\tshow slightly higher variability, the overall distributions and\n\taverages are very similar, suggesting minimal gender differences\n\tin weekly phone usage in this dataset.")

print("\n" + "-" * 80 + "\n")

# *******************************************************************
print("Part II.")
# Data
x = np.array([2,3,7,8,10,10,12,15,17,20])
n = len(x)

print("\n" + "-" * 80 + "\n")
print("Dataset: [2,3,7,8,10,10,12,15,17,20]\n")

# Format numbers, decimal
def fmt(x, decimals=8):
    if abs(x) < 1e-10:
        x = 0

    return f"{x:.{decimals}f}".rstrip('0').rstrip('.')

# Question 1: Moments about the origin (m1', m2', m3', m4')
# Computations: Powers of x & Summations
x2 = x**2
x3 = x**3
x4 = x**4

table1 = pd.DataFrame({
"x": x,
"x²": x2,
"x³": x3,
"x⁴": x4
})

print("Computations for #1.\nValues and Powers")
display(table1.style.hide(axis="index"))

sum_x = np.sum(x)
sum_x2 = np.sum(x2)
sum_x3 = np.sum(x3)
sum_x4 = np.sum(x4)

sum_table = pd.DataFrame({
"Quantity":["Σx","Σx²","Σx³","Σx⁴"],
"Value":[sum_x,sum_x2,sum_x3,sum_x4]
})

print("\nSummations")

display(
sum_table.style
.hide(axis="index")
.set_properties(subset=["Quantity"], **{"text-align":"left"})
)

# Moments of the Set
m1_prime = sum_x/n
m2_prime = sum_x2/n
m3_prime = sum_x3/n
m4_prime = sum_x4/n

set_table = pd.DataFrame({
"Moments":[
"(a) First moment (m1')",
"(b) Second moment (m2')",
"(c) Third moment (m3')",
"(d) Fourth moment (m4')"
],
"Value":[
fmt(m1_prime),
fmt(m2_prime),
fmt(m3_prime),
fmt(m4_prime)
]
})

print("\n\nAnswer for #1:\nMoments of the Set")

display(
set_table.style
.hide(axis="index")
.set_properties(subset=["Moments"], **{"text-align":"left"})
)

print("\n" + "-" * 80 + "\n")

# *******************************************************************
# Question 2: Moments about the Mean of the Set
# Computations: Deviations from mean

mean = m1_prime

d = x - mean
d2 = d**2
d3 = d**3
d4 = d**4

table2 = pd.DataFrame({
"x": x,
"x-mean": [fmt(v) for v in d],
"(x-mean)²": [fmt(v) for v in d2],
"(x-mean)³": [fmt(v) for v in d3],
"(x-mean)⁴": [fmt(v) for v in d4]
})

print("Computations for #2.\nDeviations")

display(table2.style.hide(axis="index"))

# Moments about the Mean

m1 = np.mean(d)
m2 = np.mean(d2)
m3 = np.mean(d3)
m4 = np.mean(d4)

central_table = pd.DataFrame({
"Moments":[
"(a) First moment about mean",
"(b) Second moment about mean",
"(c) Third moment about mean",
"(d) Fourth moment about mean"
],
"Value":[
fmt(m1),
fmt(m2),
fmt(m3),
fmt(m4)
]
})

print("\n\nAnswer for #2:\nMoments about the Mean of the Set")

display(
central_table.style
.hide(axis="index")
.set_properties(subset=["Moments"], **{"text-align":"left"})
)

print("\n" + "-" * 80 + "\n")

# *******************************************************************
# Question 3: Verifying relationship of m4 = m4' − 4m1'm3' + 6(m1')²m2' − 3(m1')⁴
# Computations: Formula & Verification
print("Computations for #2.\nVerify: m4 = m4' − 4m1'm3' + 6(m1')²m2' − 3(m1')⁴")
formula = (
m4_prime
- 4*m1_prime*m3_prime
+ 6*(m1_prime**2)*m2_prime
- 3*(m1_prime**4)
)

print("Fourth moment about mean / m4 = ", fmt(m4))
print("\nm4' − 4(m1')(m3') + 6(m1')²(m2') − 3(m1')⁴")
print("= 34147.6 - 4(10.4)(2090.6) + 6(10.4)²(138.4) - 3(10.4)⁴\n=", round(formula,4), "\n\n")

verify_table = pd.DataFrame({
"Expressions":[
"m4",
"Computed formula"
],
"Value":[
fmt(m4),
fmt(formula)
]
})

print("Answer for #3:\nVerification")

display(
verify_table.style
.hide(axis="index")
.set_properties(subset=["Expressions"], **{"text-align":"left"})
)

print("\nm4 = 1898.9472 = m4' − 4m1'm3' + 6(m1')²m2' − 3(m1')⁴\nSince m4 = m4' − 4m1'm3' + 6(m1')²m2' − 3(m1')⁴, then it is verified.")

print("\n" + "-" * 80 + "\n")

# *******************************************************************
# Part III: Prove: m4' = m4 + 4hm3 + 6h²m2 + h⁴
print("Part III.")
print("\n" + "-" * 80 + "\n")
print("Answer for Part III.\nProof:")

h = m1_prime

print("Let:")
print("m4' = m4 + 4hm3 + 6h²m2 + h⁴, where h = m1' =", fmt(h))
print("LHS = m4'\nRHS = m4 + 4hm3 + 6h²m2 + h⁴")

# Computations
term1 = m4
term2 = 4*h*m3
term3 = 6*(h**2)*m2
term4 = h**4

rhs = term1 + term2 + term3 + term4

proof_table = pd.DataFrame({
"Expressions":[
"m4",
"4hm3",
"6h²m2",
"h⁴",
"RHS",
"LHS"
],
"Value":[
fmt(term1),
fmt(term2),
fmt(term3),
fmt(term4),
fmt(rhs),
fmt(m4_prime)
]
})

print("\nComputations of Proof")

display(
proof_table.style
.hide(axis="index")
.set_properties(subset=["Expressions"], **{"text-align":"left"})
)

# Print of Proof
print("\nCompute the RHS:")
print("m4 + 4hm3 + 6h²m2 + h⁴, where h = m1'")
print("=",fmt(term1), "+", fmt(term2), "+", fmt(term3), "+", fmt(term4))
print("RHS =", fmt(rhs))

print("\nLHS = m4' =", fmt(m4_prime))

print("Conclusion:")
if abs(rhs - m4_prime) < 1e-8:
    print("\nSince LHS = RHS, the identity is VERIFIED.")
else:
    print("\nThe identity is NOT satisfied.")

print("\n" + "-" * 80 + "\n")

from scipy.stats import t
#APM 1111 - SA1 by Borja, Rachelle Erika D.

# Part IV.
print("Part IV.")
# *******************************************************************
# Format numbers, decimal
def fmt(x, decimals=6):
    if abs(x) < 1e-10:
        x = 0
    return f"{x:.{decimals}f}".rstrip('0').rstrip('.')

# *******************************************************************
# Question 1: Area between -t1 and t1 = 0.90 and v=20
v1 = 20
central = 0.90

remaining = 1 - central
tail = remaining / 2
cdf_value = 1 - tail

t1_q1 = round(t.ppf(cdf_value, v1),3)

table_q1 = pd.DataFrame({
"Step":[
"Central Area",
"Remaining Area",
"Area per Tail",
"CDF (t.ppf())",
"Computed t1"
],
"Computation":[
"0.90",
"1 - 0.90",
"(1-0.90)/2",
"1 - 0.05",
"t.ppf(0.95,20)"
],
"Value":[
fmt(central),
fmt(remaining),
fmt(tail),
fmt(cdf_value),
fmt(t1_q1,3)
]
})

print("\n" + "-" * 80 + "\n")
print("Number 1 Computation: Area between -t1 and t1 = 0.90 and v=20")
display(table_q1.style
.hide(axis="index")
.set_properties(subset=["Step"], **{"text-align":"left"})
)

print("\n" + "-" * 80 + "\n")

# *******************************************************************
# Question 2: Area to the left of -t1 = 0.025 and v=20
v2 = 20
left_prob = 0.025

neg_t = t.ppf(left_prob, v2)
t1_q2 = round(abs(neg_t),3)

table_q2 = pd.DataFrame({
"Step":[
"Left Tail Probability",
"t.ppf(0.025,20)",
"Absolute value gives t1"
],
"Computation":[
"P(T ≤ -t1) = 0.025",
"t.ppf(0.025,20)",
"|t|"
],
"Value":[
fmt(left_prob),
fmt(neg_t,3),
fmt(t1_q2,3)
]
})

print("Number 2 Computation: Area to the left of -t1 = 0.025 and v=20")
display(table_q2.style
.hide(axis="index")
.set_properties(subset=["Step"], **{"text-align":"left"})
)

print("\n" + "-" * 80 + "\n")

# *******************************************************************
# Question 3: Combined tails = 0.01 and v=5
v3 = 5
combined = 0.01

tail_each = combined / 2
cdf_value = 1 - tail_each

t1_q3 = round(t.ppf(cdf_value, v3),3)

table_q3 = pd.DataFrame({
"Step":[
"Combined Tail Area",
"Area per Tail",
"CDF (t.ppf())",
"Computed t1"
],
"Computation":[
"0.01",
"0.01/2",
"1 - 0.005",
"t.ppf(0.995,5)"
],
"Value":[
fmt(combined),
fmt(tail_each),
fmt(cdf_value),
fmt(t1_q3,3)
]
})

print("Number 3 Computation: Combined tails = 0.01 and v=5")
display(table_q3.style
.hide(axis="index")
.set_properties(subset=["Step"], **{"text-align":"left"})
)

print("\n" + "-" * 80 + "\n")

# *******************************************************************
# Question 4: Area to the right of t1 = 0.55 and v=16
v4 = 16
right_area = 0.55
left_area = 1 - right_area

t1_q4 = round(t.ppf(left_area, v4),4)

table_q4 = pd.DataFrame({
"Step":[
"Right Tail Probability",
"Convert to Left Probability",
"CDF (t.ppf())",
"Computed t1"
],
"Computation":[
"P(T ≥ t1) = 0.55",
"1 - 0.55",
"t.ppf(0.45,16)",
"Result"
],
"Value":[
fmt(right_area),
fmt(left_area),
fmt(left_area),
fmt(t1_q4,3)
]
})

print("Number 4 Computation: Area to the right of t1 = 0.55 and v=16")
display(table_q4.style
.hide(axis="index")
.set_properties(subset=["Step"], **{"text-align":"left"})
)

print("\n" + "-" * 80 + "\n")

# Final Answers Summary
summary = pd.DataFrame({
"Questions":[
"#1",
"#2",
"#3",
"#4"
],
"t1":[
fmt(t1_q1,3),
fmt(t1_q2,3),
fmt(t1_q3,3),
fmt(t1_q4,3)
]
})

print("Summary of Final Answers for Part IV.")
display(summary.style
.hide(axis="index")
.set_properties(subset=["Questions"], **{"text-align":"left"})
)

print("\n" + "-" * 80 + "\n")

--------------------------------------------------------------------------------

Borja_SA1 - Part I.

--------------------------------------------------------------------------------

Descriptive Statistical Summaries of the Entire Dataset

--------------------------------------------------------------------------------

Descriptive Statistical Summaries Grouped by Gender

--------------------------------------------------------------------------------

Short Statistical Report

1. Descriptive Statistics of the Entire Dataset
	The dataset contains 100 observations of weekly phone usage.
	The mean usage is 9.76 hours and the median is 10.00 hours,
	indicating that the typical weekly usage is around 10 hours.
	The standard deviation is 1.96 hours, showing moderate
	variability among individuals. Phone usage ranges from
	4–15 hours. The skewness is close to zero, suggesting a roughly
	symmetric distribution, while the kurtosis is also near zero,
	indicating a distribution similar to normal. The middle 50%
	of the data lies between 9 and 11 hours based on the quartiles.

2. Comparison Across Gender
	Both gender groups show very similar phone usage patterns.
	Males have a mean of 9.82 hours, while females have a mean of
	9.70 hours. The standard deviation for males (≈2.15) is slightly
	larger than for females (≈1.78), indicating slightly greater
	variability among males. The usage ranges are 4–15 hours for
	males and 6–14 hours for females, but both groups have medians
	close to 10 hours like 10.0 hours for males, and 9.50 hours for
	females, suggesting similar central tendencies.

3. Interpretation of the 95% Confidence Intervals
	The 95% confidence interval for the overall mean is approximately
	(9.37, 10.15) hours, meaning the true population mean weekly phone
	usage likely falls within this range. For the gender groups, the
	intervals are approximately (9.21, 10.43) for males and (9.20, 10.20)
	for females. Since these intervals overlap, there is no strong
	evidence of a difference in average phone usage between genders.

4. Observed Patterns
	Overall, both genders display similar phone usage patterns, with
	most values concentrated around 9–11 hours per week. While males
	show slightly higher variability, the overall distributions and
	averages are very similar, suggesting minimal gender differences
	in weekly phone usage in this dataset.

--------------------------------------------------------------------------------

Part II.

--------------------------------------------------------------------------------

Dataset: [2,3,7,8,10,10,12,15,17,20]

Computations for #1.
Values and Powers

Summations

Answer for #1:
Moments of the Set

--------------------------------------------------------------------------------

Computations for #2.
Deviations

Answer for #2:
Moments about the Mean of the Set

--------------------------------------------------------------------------------

Computations for #2.
Verify: m4 = m4' − 4m1'm3' + 6(m1')²m2' − 3(m1')⁴
Fourth moment about mean / m4 =  1898.9472

m4' − 4(m1')(m3') + 6(m1')²(m2') − 3(m1')⁴
= 34147.6 - 4(10.4)(2090.6) + 6(10.4)²(138.4) - 3(10.4)⁴
= 1898.9472


Answer for #3:
Verification

m4 = 1898.9472 = m4' − 4m1'm3' + 6(m1')²m2' − 3(m1')⁴
Since m4 = m4' − 4m1'm3' + 6(m1')²m2' − 3(m1')⁴, then it is verified.

--------------------------------------------------------------------------------

Part III.

--------------------------------------------------------------------------------

Answer for Part III.
Proof:
Let:
m4' = m4 + 4hm3 + 6h²m2 + h⁴, where h = m1' = 10.4
LHS = m4'
RHS = m4 + 4hm3 + 6h²m2 + h⁴

Computations of Proof

Compute the RHS:
m4 + 4hm3 + 6h²m2 + h⁴, where h = m1'
= 1898.9472 + 925.5168 + 19624.5504 + 11698.5856
RHS = 34147.6

LHS = m4' = 34147.6
Conclusion:

Since LHS = RHS, the identity is VERIFIED.

--------------------------------------------------------------------------------

Part IV.

--------------------------------------------------------------------------------

Number 1 Computation: Area between -t1 and t1 = 0.90 and v=20

--------------------------------------------------------------------------------

Number 2 Computation: Area to the left of -t1 = 0.025 and v=20

--------------------------------------------------------------------------------

Number 3 Computation: Combined tails = 0.01 and v=5

--------------------------------------------------------------------------------

Number 4 Computation: Area to the right of t1 = 0.55 and v=16

--------------------------------------------------------------------------------

Summary of Final Answers for Part IV.

--------------------------------------------------------------------------------